#!/usr/bin/env python3
"""
Configure Environment for Real Google APIs Testing
"""

import os
import sys

def configure_real_apis():
    """Configure environment for real Google APIs testing"""
    print("🔧 Configuring Environment for Real Google APIs Testing")
    print("=" * 60)
    
    # Read current .env file
    env_file = '.env'
    env_content = {}
    
    if os.path.exists(env_file):
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_content[key] = value
    
    # Configuration changes for real API testing
    changes = {
        'USE_GOOGLE_APIS': 'true',
        'FALLBACK_TO_SERPAPI': 'false',
        'MIGRATE_SERP_ANALYSIS': 'true',
        'MIGRATE_COMPETITOR_ANALYSIS': 'true',
        'MIGRATE_CONTENT_ANALYSIS': 'true',
        'MIGRATE_ENTITY_ANALYSIS': 'true'
    }
    
    # Apply changes
    for key, value in changes.items():
        env_content[key] = value
    
    # Write back to .env file
    with open(env_file, 'w') as f:
        f.write("# Google APIs Configuration for Real Data Testing\n")
        f.write("# Generated by configure_real_apis.py\n\n")
        
        for key, value in env_content.items():
            f.write(f"{key}={value}\n")
    
    print("✅ Environment configured for real Google APIs testing")
    print("\n📋 Applied changes:")
    for key, value in changes.items():
        print(f"  {key}={value}")
    
    # Check required keys
    required_keys = [
        'GOOGLE_API_KEY',
        'GOOGLE_CUSTOM_SEARCH_ENGINE_ID',
        'GEMINI_API_KEY'
    ]
    
    missing_keys = []
    for key in required_keys:
        if key not in env_content or not env_content[key] or env_content[key] == 'your_key_here':
            missing_keys.append(key)
    
    if missing_keys:
        print(f"\n❌ Missing required API keys:")
        for key in missing_keys:
            print(f"  - {key}")
        print("\n📋 Setup Instructions:")
        print("1. Get Google API key from: https://console.cloud.google.com/")
        print("2. Create Custom Search Engine: https://cse.google.com/")
        print("3. Add these keys to your .env file:")
        for key in missing_keys:
            print(f"   {key}=your_actual_key_here")
        return False
    else:
        print("\n✅ All required API keys are configured")
        return True

if __name__ == "__main__":
    success = configure_real_apis()
    
    if success:
        print("\n🎯 Ready for real data testing!")
        print("Run these commands:")
        print("1. python test_google_apis_connection.py")
        print("2. python test_real_keyword_processing.py")
        print("3. python test_phase_2_4_keyword_processor.py")
    else:
        print("\n⚠️ Please configure your API keys first")
        print("Follow the instructions in SETUP_REAL_GOOGLE_APIS.md")
    
    sys.exit(0 if success else 1)
